# Site settings
title: 回未视戒 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "当视戒变的多，唯一的办法便是回到未来"  # 一句话描述你的博客
baseurl: ""
url: "http://huiweishijie.com"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "XIAHIBB" # 填写作者信息：名字
  email: xiahibb@gmail.com # 填写作者信息：邮箱
  bio: "XIAHIBB在黑暗的设计中探索自己的未来，目前从事的是品牌LOGO的设计。" # 填写作者信息：博客描述

# Data
gavatar: img/green.jpg # 浏览器地址栏小图标，可自定义更改
favicon: img/green.jpg # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username:   
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "XIAHIBB" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :  <script id="dsq-count-scr" src="//huiweishijie.disqus.com/count.js" async></script>

<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://huiweishijie.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-126330089-2" # 填写你  google_analytics id
google_verify: "https://www.googletagmanager.com/gtag/js?id=UA-126330089-2"
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
google-site-verification: google3643de2f0ecebcc4.html


